version: '3.4'

services:
  owlcarousel:
    image: owlcarousel
    build:
      context: js/owl/OwlCarousel2-2.3.4
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./dist/owl.carousel.js"]
